version: '3'
services:
  manage_students:
    build: .
    ports:
    - 8001:8001
    command: ["uvicorn", "manage_students.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]
    environment:
    - AWS_ACCESS_KEY_ID=xxx
    - AWS_SECRET_ACCESS_KEY=xxx
    - PYTHONPATH=manage_students
    - DDB_HOST=http://dynamodb:8081
    - DDB_TABLE=exam_scores-local
    - AWS_REGION=ap-northeast-1
    volumes:
    - $PWD/manage_students:/manage_students
    links:
    - dynamodb 
  dynamodb:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /ddb-data  -port 8081
    environment:
    - AWS_DEFAULT_REGION=ap-northeast-1
    volumes:
    - $PWD/ddb-data:/ddb-data
    ports:
    - 8081:8081
  dynamodb-admin:
    image: instructure/dynamo-local-admin
    links:
    - dynamodb 
    environment:
    - DYNAMO_ENDPOINT=http://dynamodb:8081
    - AWS_DEFAULT_REGION=ap-northeast-1
    ports:
    - 8000:8000
